// <auto-generated />
using System;
using CbsAp.Infrastracture.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CbsAp.Infrastracture.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250113002201_RevertPermissionGroupKeys")]
    partial class RevertPermissionGroupKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CbsAp.Domain.Entities.Dashboard.Notice", b =>
                {
                    b.Property<long>("NoticeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NoticeID"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Heading")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Message")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("NoticeID")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.ToTable("Notice", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.EntityProfileManagement.EntityProfile", b =>
                {
                    b.Property<long>("EntityProfileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EntityProfileID"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ERPFinanceSystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("EntityCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxID")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("EntityProfileID")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.ToTable("EntityProfile", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.ControlElement", b =>
                {
                    b.Property<long>("ControlID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ControlID"));

                    b.Property<string>("ActionName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActionType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("OperationID")
                        .HasColumnType("bigint");

                    b.HasKey("ControlID")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.HasIndex("OperationID")
                        .IsUnique();

                    b.ToTable("ControlElement", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.Menu", b =>
                {
                    b.Property<long>("MenuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MenuID"));

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RouterLink")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MenuID")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.ToTable("Menu", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.MenuItem", b =>
                {
                    b.Property<long>("MenuItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MenuItemID"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("MenuID")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.Property<string>("RouterLink")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MenuItemID")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.HasIndex("MenuID");

                    b.ToTable("MenuItem", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.Operation", b =>
                {
                    b.Property<long>("OperationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OperationID"));

                    b.Property<string>("ApplyOperationIn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OperationName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Panel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OperationID")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.ToTable("Operation", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.Permission", b =>
                {
                    b.Property<long>("PermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PermissionID"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PermissionID")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.ToTable("Permission", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.PermissionGroup", b =>
                {
                    b.Property<long>("PermissionGroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PermissionGroupID"));

                    b.Property<bool>("Access")
                        .HasColumnType("bit");

                    b.Property<long>("OperationID")
                        .HasColumnType("bigint");

                    b.Property<long>("PermissionID")
                        .HasColumnType("bigint");

                    b.HasKey("PermissionGroupID")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.HasAlternateKey("PermissionID", "OperationID");

                    b.HasIndex("OperationID");

                    b.ToTable("PermissionGroup", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.RolePermissionGroup", b =>
                {
                    b.Property<long>("RolePermissionGroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RolePermissionGroupID"));

                    b.Property<long>("PermissionID")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleID")
                        .HasColumnType("bigint");

                    b.HasKey("RolePermissionGroupID")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.HasAlternateKey("RoleID", "PermissionID");

                    b.HasIndex("PermissionID");

                    b.ToTable("RolePermissionGroup", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.RoleManagement.Role", b =>
                {
                    b.Property<long>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoleID"));

                    b.Property<decimal?>("AuthorisationLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("CanBeAddedToInvoice")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("RoleManager1")
                        .HasColumnType("bigint");

                    b.Property<long?>("RoleManager2")
                        .HasColumnType("bigint");

                    b.Property<string>("RoleName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("RoleID")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.HasIndex("RoleManager1");

                    b.HasIndex("RoleManager2");

                    b.ToTable("Role", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.RoleManagement.RoleEntity", b =>
                {
                    b.Property<long>("RoleEntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoleEntityID"));

                    b.Property<long>("EntityProfileID")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleID")
                        .HasColumnType("bigint");

                    b.HasKey("RoleEntityID")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.HasAlternateKey("RoleID", "EntityProfileID");

                    b.HasIndex("EntityProfileID");

                    b.ToTable("RoleEntity", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.RoleManagement.RoleReminderNotification", b =>
                {
                    b.Property<long>("RoleReminderNotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoleReminderNotificationID"));

                    b.Property<int?>("ForwardToLevel1Manager")
                        .HasColumnType("int");

                    b.Property<int?>("ForwardToLevel2Manager")
                        .HasColumnType("int");

                    b.Property<int?>("InvoiceDueDateNotification")
                        .HasColumnType("int");

                    b.Property<int?>("InvoiceEscalateToLevel1ManagerNotification")
                        .HasColumnType("int");

                    b.Property<bool>("IsNewInvoiceReceiveNotification")
                        .HasColumnType("bit");

                    b.Property<long>("RoleID")
                        .HasColumnType("bigint");

                    b.HasKey("RoleReminderNotificationID");

                    b.HasAlternateKey("RoleID");

                    b.ToTable("RoleReminderNotification", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.RoleManagement.UserRole", b =>
                {
                    b.Property<long>("UserRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserRoleID"));

                    b.Property<long>("RoleID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserAccountID")
                        .HasColumnType("bigint");

                    b.HasKey("UserRoleID")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.HasAlternateKey("UserAccountID", "RoleID");

                    b.HasIndex("RoleID");

                    b.ToTable("UserRole", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.TaxCodes.TaxCode", b =>
                {
                    b.Property<long>("TaxCodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TaxCodeID"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("EntityID")
                        .HasColumnType("bigint");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TaxCodeName")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<int>("TaxRate")
                        .HasColumnType("int");

                    b.HasKey("TaxCodeID")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.HasIndex("EntityID");

                    b.ToTable("TaxCode", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.UserManagement.UserAccount", b =>
                {
                    b.Property<long>("UserAccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserAccountID"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUserPartialDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserAccountID")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.HasAlternateKey("UserID");

                    b.ToTable("UserAccount", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.UserManagement.UserLogInfo", b =>
                {
                    b.Property<long>("UserLogInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserLogInfoID"));

                    b.Property<string>("ConfirmationToken")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("MaximuPasswordAge")
                        .HasColumnType("int");

                    b.Property<int?>("MaximumLogInAttemp")
                        .HasColumnType("int");

                    b.Property<int?>("MinimumPasswordAge")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("PasswordrecoveryToken")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTimeOffset?>("RecoveryTokenTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("TokenGenerationTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("UserAccountID")
                        .HasColumnType("bigint");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserLogInfoID");

                    b.HasAlternateKey("UserID");

                    b.HasIndex("UserAccountID")
                        .IsUnique();

                    b.ToTable("UserLogInfo", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.ControlElement", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.PermissionManagement.Operation", "Operation")
                        .WithOne("ControlElement")
                        .HasForeignKey("CbsAp.Domain.Entities.PermissionManagement.ControlElement", "OperationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.MenuItem", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.PermissionManagement.Menu", "Menu")
                        .WithMany("Items")
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.PermissionGroup", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.PermissionManagement.Operation", "Operations")
                        .WithMany("PermissionGroups")
                        .HasForeignKey("OperationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CbsAp.Domain.Entities.PermissionManagement.Permission", "Permission")
                        .WithMany("PermissionGroups")
                        .HasForeignKey("PermissionID");

                    b.Navigation("Operations");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.RolePermissionGroup", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.PermissionManagement.PermissionGroup", "PermissionGroup")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionID")
                        .HasPrincipalKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CbsAp.Domain.Entities.RoleManagement.Role", "Role")
                        .WithMany("RolePermissionGroups")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionGroup");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.RoleManagement.Role", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.RoleManagement.Role", "RelatedRoleManager1")
                        .WithMany()
                        .HasForeignKey("RoleManager1");

                    b.HasOne("CbsAp.Domain.Entities.RoleManagement.Role", "RelatedRoleManager2")
                        .WithMany()
                        .HasForeignKey("RoleManager2");

                    b.Navigation("RelatedRoleManager1");

                    b.Navigation("RelatedRoleManager2");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.RoleManagement.RoleEntity", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.EntityProfileManagement.EntityProfile", "EntityProfile")
                        .WithMany("RoleEntities")
                        .HasForeignKey("EntityProfileID");

                    b.HasOne("CbsAp.Domain.Entities.RoleManagement.Role", "Role")
                        .WithMany("RoleEntities")
                        .HasForeignKey("RoleID");

                    b.Navigation("EntityProfile");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.RoleManagement.RoleReminderNotification", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.RoleManagement.Role", "Role")
                        .WithOne("RoleReminderNotification")
                        .HasForeignKey("CbsAp.Domain.Entities.RoleManagement.RoleReminderNotification", "RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.RoleManagement.UserRole", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.RoleManagement.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CbsAp.Domain.Entities.UserManagement.UserAccount", "UserAccount")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserAccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.TaxCodes.TaxCode", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.EntityProfileManagement.EntityProfile", "EntityProfile")
                        .WithMany()
                        .HasForeignKey("EntityID");

                    b.Navigation("EntityProfile");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.UserManagement.UserLogInfo", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.UserManagement.UserAccount", "UserAccount")
                        .WithOne("UserLogInfo")
                        .HasForeignKey("CbsAp.Domain.Entities.UserManagement.UserLogInfo", "UserAccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.EntityProfileManagement.EntityProfile", b =>
                {
                    b.Navigation("RoleEntities");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.Menu", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.Operation", b =>
                {
                    b.Navigation("ControlElement")
                        .IsRequired();

                    b.Navigation("PermissionGroups");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.Permission", b =>
                {
                    b.Navigation("PermissionGroups");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.PermissionGroup", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.RoleManagement.Role", b =>
                {
                    b.Navigation("RoleEntities");

                    b.Navigation("RolePermissionGroups");

                    b.Navigation("RoleReminderNotification")
                        .IsRequired();

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.UserManagement.UserAccount", b =>
                {
                    b.Navigation("UserLogInfo")
                        .IsRequired();

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
