// <auto-generated />
using System;
using CbsAp.Infrastracture.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CbsAp.Infrastracture.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251001054237_AddAAccountAuditFields")]
    partial class AddAAccountAuditFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CbsAp.Domain.Entities.Dashboard.Notice", b =>
                {
                    b.Property<long>("NoticeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NoticeID"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Heading")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Message")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("NoticeID")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.ToTable("Notice", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Entity.EntityMatchingConfig", b =>
                {
                    b.Property<long>("MatchingConfigID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MatchingConfigID"));

                    b.Property<string>("ConfigType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("DollarAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("EntityProfileID")
                        .HasColumnType("bigint");

                    b.Property<string>("InvoiceMatchBasis")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MatchingLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("PercentageAmt")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MatchingConfigID");

                    b.HasIndex("EntityProfileID");

                    b.ToTable("EntityMatchingConfig", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Entity.EntityProfile", b =>
                {
                    b.Property<long>("EntityProfileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EntityProfileID"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("DefaultInvoiceDueInDays")
                        .HasColumnType("int");

                    b.Property<string>("ERPFinanceSystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("EntityCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.Property<bool?>("InvAllowPresetAmount")
                        .HasColumnType("bit");

                    b.Property<bool?>("InvAllowPresetDimension")
                        .HasColumnType("bit");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("TaxDollarAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TaxID")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<decimal?>("TaxPercentageAmt")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EntityProfileID");

                    b.ToTable("EntityProfile", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Invoicing.Account", b =>
                {
                    b.Property<long>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AccountID"));

                    b.Property<string>("AccountName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Dimension1")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Dimension2")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Dimension3")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Dimension4")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Dimension5")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Dimension6")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Dimension7")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Dimension8")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<long?>("EntityProfileID")
                        .HasColumnType("bigint");

                    b.Property<string>("FreeField1")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("FreeField2")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("FreeField3")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTaxCodeMandatory")
                        .HasColumnType("bit");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("TaxCodeID")
                        .HasColumnType("bigint");

                    b.Property<string>("TaxCodeName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AccountID");

                    b.HasIndex("EntityProfileID")
                        .IsUnique()
                        .HasFilter("[EntityProfileID] IS NOT NULL");

                    b.HasIndex("TaxCodeID")
                        .IsUnique()
                        .HasFilter("[TaxCodeID] IS NOT NULL");

                    b.ToTable("Account", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Invoicing.InvAllocLine", b =>
                {
                    b.Property<long>("InvAllocLineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InvAllocLineID"));

                    b.Property<string>("Account")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long?>("InvoiceID")
                        .HasColumnType("bigint");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("LineAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LineApproved")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LineDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("LineNetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("LineNo")
                        .HasColumnType("bigint");

                    b.Property<decimal>("LineTaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PoLineNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PoNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<long?>("TaxCodeID")
                        .HasColumnType("bigint");

                    b.HasKey("InvAllocLineID");

                    b.HasIndex("InvoiceID");

                    b.HasIndex("TaxCodeID");

                    b.ToTable("InvAllocLine", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Invoicing.InvAllocLineDimension", b =>
                {
                    b.Property<long>("InvAllocLineDimensionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InvAllocLineDimensionID"));

                    b.Property<string>("DimensionKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DimensionValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("InvAllocLineID")
                        .HasColumnType("bigint");

                    b.HasKey("InvAllocLineDimensionID");

                    b.HasIndex("InvAllocLineID");

                    b.ToTable("InvAllocLineDimension", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Invoicing.InvAllocLineFreeField", b =>
                {
                    b.Property<long>("InvAllocLineFieldID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InvAllocLineFieldID"));

                    b.Property<string>("FieldKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FieldValue")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("InvAllocLineID")
                        .HasColumnType("bigint");

                    b.HasKey("InvAllocLineFieldID");

                    b.HasIndex("InvAllocLineID");

                    b.ToTable("InvAllocLineFreeField", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Invoicing.InvRoutingFlow", b =>
                {
                    b.Property<long>("InvRoutingFlowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InvRoutingFlowID"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("EntityProfileID")
                        .HasColumnType("bigint");

                    b.Property<string>("InvRoutingFlowName")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MatchReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("SupplierInfoID")
                        .HasColumnType("bigint");

                    b.HasKey("InvRoutingFlowID");

                    b.HasIndex("EntityProfileID");

                    b.HasIndex("SupplierInfoID");

                    b.ToTable("InvRoutingFlow", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Invoicing.InvRoutingFlowLevels", b =>
                {
                    b.Property<long>("InvRoutingFlowLevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InvRoutingFlowLevelID"));

                    b.Property<long>("InvRoutingFlowID")
                        .HasColumnType("bigint");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<long>("RoleID")
                        .HasColumnType("bigint");

                    b.HasKey("InvRoutingFlowLevelID");

                    b.HasIndex("InvRoutingFlowID");

                    b.HasIndex("RoleID");

                    b.ToTable("InvRoutingFlowLevels", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Invoicing.Invoice", b =>
                {
                    b.Property<long>("InvoiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InvoiceID"));

                    b.Property<string>("ApprovedUser")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApproverRole")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("EntityProfileID")
                        .HasColumnType("bigint");

                    b.Property<string>("GrNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageID")
                        .HasMaxLength(16)
                        .HasColumnType("char(16)");

                    b.Property<DateTimeOffset?>("InvoiceDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InvoiceNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MapID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PaymentTerm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PoNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("QueueType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ScanDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("StatusType")
                        .HasColumnType("int");

                    b.Property<string>("SuppBankAccount")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("SupplierInfoID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("TaxCodeID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InvoiceID");

                    b.HasIndex("EntityProfileID");

                    b.HasIndex("SupplierInfoID");

                    b.HasIndex("TaxCodeID");

                    b.ToTable("Invoice", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Invoicing.InvoiceActivityLog", b =>
                {
                    b.Property<long>("ActivityLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ActivityLogID"));

                    b.Property<int?>("Action")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<long>("InvoiceID")
                        .HasColumnType("bigint");

                    b.Property<int?>("PreviousStatus")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ActivityLogID");

                    b.HasIndex("InvoiceID");

                    b.ToTable("InvoiceActivityLog", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Invoicing.InvoiceAttachnment", b =>
                {
                    b.Property<long>("InvoiceAttachnmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InvoiceAttachnmentID"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FileType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("InvoiceID")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StorageFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("InvoiceAttachnmentID");

                    b.HasIndex("InvoiceID");

                    b.ToTable("InvoiceAttachnment", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Invoicing.InvoiceComment", b =>
                {
                    b.Property<long>("InvoiceCommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InvoiceCommentID"));

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("InvoiceID")
                        .HasColumnType("bigint");

                    b.HasKey("InvoiceCommentID");

                    b.HasIndex("InvoiceID");

                    b.ToTable("InvoiceComment", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PO.PurchaseOrder", b =>
                {
                    b.Property<long>("PurchaseOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PurchaseOrderID"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<long?>("EntityProfileID")
                        .HasColumnType("bigint");

                    b.Property<string>("FreeField1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FreeField2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FreeField3")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MatchReference1")
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.Property<string>("MatchReference2")
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.Property<decimal?>("NetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PoNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SupplierInfoID")
                        .HasColumnType("bigint");

                    b.Property<string>("SupplierTaxID")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PurchaseOrderID");

                    b.HasIndex("EntityProfileID");

                    b.HasIndex("SupplierInfoID");

                    b.ToTable("PurchaseOrder", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PO.PurchaseOrderLine", b =>
                {
                    b.Property<long>("PurchaseOrderLineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PurchaseOrderLineID"));

                    b.Property<long?>("AccountID")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.Property<string>("FreeField1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FreeField2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FreeField3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("FullyInvoiced")
                        .HasColumnType("bit");

                    b.Property<decimal?>("InvoicedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Item")
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LineNo")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("NetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("PurchaseOrderID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("SpareAmount1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SpareAmount2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SpareAmount3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("TaxCodeID")
                        .HasColumnType("bigint");

                    b.Property<string>("Unit")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("PurchaseOrderLineID");

                    b.HasIndex("AccountID");

                    b.HasIndex("PurchaseOrderID");

                    b.HasIndex("TaxCodeID");

                    b.ToTable("PurchaseOrderLine", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PO.PurchaseOrderMatchTracking", b =>
                {
                    b.Property<long>("PurchaseOrderMatchTrackingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PurchaseOrderMatchTrackingID"));

                    b.Property<string>("Account")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("InvAllocLineID")
                        .HasColumnType("bigint");

                    b.Property<long?>("InvoiceID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsSystemMatching")
                        .HasColumnType("bit");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("MatchingDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("MatchingStatus")
                        .HasColumnType("int");

                    b.Property<decimal?>("NetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("PurchaseOrderID")
                        .HasColumnType("bigint");

                    b.Property<long>("PurchaseOrderLineID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("RemainingQty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PurchaseOrderMatchTrackingID");

                    b.HasIndex("InvAllocLineID");

                    b.HasIndex("InvoiceID");

                    b.HasIndex("PurchaseOrderID");

                    b.HasIndex("PurchaseOrderLineID");

                    b.ToTable("PurchaseOrderMatchTracking", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.ControlElement", b =>
                {
                    b.Property<long>("ControlID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ControlID"));

                    b.Property<string>("ActionName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActionType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("OperationID")
                        .HasColumnType("bigint");

                    b.HasKey("ControlID")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.HasIndex("OperationID")
                        .IsUnique();

                    b.ToTable("ControlElement", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.Menu", b =>
                {
                    b.Property<long>("MenuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MenuID"));

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("OperationID")
                        .HasColumnType("bigint");

                    b.Property<string>("RouterLink")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MenuID");

                    b.HasIndex("OperationID");

                    b.ToTable("Menu", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.MenuItem", b =>
                {
                    b.Property<long>("MenuItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MenuItemID"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("MenuID")
                        .HasColumnType("bigint");

                    b.Property<string>("RouterLink")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MenuItemID");

                    b.HasIndex("MenuID");

                    b.ToTable("MenuItem", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.Operation", b =>
                {
                    b.Property<long>("OperationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OperationID"));

                    b.Property<string>("ApplyOperationIn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OperationName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Panel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OperationID");

                    b.ToTable("Operation", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.Permission", b =>
                {
                    b.Property<long>("PermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PermissionID"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PermissionID")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.ToTable("Permission", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.PermissionGroup", b =>
                {
                    b.Property<long>("PermissionGroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PermissionGroupID"));

                    b.Property<bool>("Access")
                        .HasColumnType("bit");

                    b.Property<long>("OperationID")
                        .HasColumnType("bigint");

                    b.Property<long>("PermissionID")
                        .HasColumnType("bigint");

                    b.HasKey("PermissionGroupID")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.HasIndex("OperationID");

                    b.HasIndex("PermissionID", "OperationID");

                    b.ToTable("PermissionGroup", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.RolePermissionGroup", b =>
                {
                    b.Property<long>("RolePermissionGroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RolePermissionGroupID"));

                    b.Property<long?>("PermissionGroupID")
                        .HasColumnType("bigint");

                    b.Property<long>("PermissionID")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleID")
                        .HasColumnType("bigint");

                    b.HasKey("RolePermissionGroupID")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.HasAlternateKey("RoleID", "PermissionID");

                    b.HasIndex("PermissionGroupID");

                    b.HasIndex("PermissionID");

                    b.ToTable("RolePermissionGroup", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.RoleManagement.Role", b =>
                {
                    b.Property<long>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoleID"));

                    b.Property<decimal?>("AuthorisationLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("CanBeAddedToInvoice")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("RoleManager1")
                        .HasColumnType("bigint");

                    b.Property<long?>("RoleManager2")
                        .HasColumnType("bigint");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("RoleID")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.HasIndex("RoleManager1");

                    b.HasIndex("RoleManager2");

                    b.ToTable("Role", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.RoleManagement.RoleEntity", b =>
                {
                    b.Property<long>("RoleEntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoleEntityID"));

                    b.Property<long>("EntityProfileID")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleID")
                        .HasColumnType("bigint");

                    b.HasKey("RoleEntityID")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.HasAlternateKey("RoleID", "EntityProfileID");

                    b.HasIndex("EntityProfileID");

                    b.ToTable("RoleEntity", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.RoleManagement.RoleReminderNotification", b =>
                {
                    b.Property<long>("RoleReminderNotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoleReminderNotificationID"));

                    b.Property<int?>("ForwardToLevel1Manager")
                        .HasColumnType("int");

                    b.Property<int?>("ForwardToLevel2Manager")
                        .HasColumnType("int");

                    b.Property<int?>("InvoiceDueDateNotification")
                        .HasColumnType("int");

                    b.Property<int?>("InvoiceEscalateToLevel1ManagerNotification")
                        .HasColumnType("int");

                    b.Property<bool>("IsNewInvoiceReceiveNotification")
                        .HasColumnType("bit");

                    b.Property<long>("RoleID")
                        .HasColumnType("bigint");

                    b.HasKey("RoleReminderNotificationID");

                    b.HasAlternateKey("RoleID");

                    b.ToTable("RoleReminderNotification", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.RoleManagement.UserRole", b =>
                {
                    b.Property<long>("UserRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserRoleID"));

                    b.Property<long>("RoleID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserAccountID")
                        .HasColumnType("bigint");

                    b.HasKey("UserRoleID")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.HasAlternateKey("UserAccountID", "RoleID");

                    b.HasIndex("RoleID");

                    b.ToTable("UserRole", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Supplier.SupplierInfo", b =>
                {
                    b.Property<long>("SupplierInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SupplierInfoID"));

                    b.Property<long?>("AccountID")
                        .HasColumnType("bigint");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(90)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(90)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("AddressLine3")
                        .HasMaxLength(90)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("AddressLine4")
                        .HasMaxLength(90)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("AddressLine5")
                        .HasMaxLength(90)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("AddressLine6")
                        .HasMaxLength(90)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Contact")
                        .HasMaxLength(90)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(90)
                        .HasColumnType("NVARCHAR");

                    b.Property<long?>("EntityProfileID")
                        .HasColumnType("bigint");

                    b.Property<string>("FreeField1")
                        .HasMaxLength(90)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("FreeField2")
                        .HasMaxLength(90)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("FreeField3")
                        .HasMaxLength(90)
                        .HasColumnType("NVARCHAR");

                    b.Property<long?>("InvRoutingFlowID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Notes")
                        .HasMaxLength(400)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("PaymentTerms")
                        .HasMaxLength(4)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("SupplierID")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("SupplierTaxID")
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR");

                    b.Property<long?>("TaxCodeID")
                        .HasColumnType("bigint");

                    b.Property<string>("Telephone")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("SupplierInfoID");

                    b.HasIndex("AccountID");

                    b.HasIndex("EntityProfileID");

                    b.HasIndex("InvRoutingFlowID");

                    b.HasIndex("TaxCodeID");

                    b.ToTable("SupplierInfo", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.System.SystemVariable", b =>
                {
                    b.Property<long>("SystemVariableID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SystemVariableID"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("SystemVariableID")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.ToTable("SystemVariable", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.TaxCodes.TaxCode", b =>
                {
                    b.Property<long>("TaxCodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TaxCodeID"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("EntityID")
                        .HasColumnType("bigint");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TaxCodeName")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TaxCodeID")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.HasIndex("EntityID");

                    b.ToTable("TaxCode", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.UserManagement.PasswordHistory", b =>
                {
                    b.Property<long>("PasswordHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PasswordHistoryID"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR");

                    b.Property<long>("UserAccountID")
                        .HasColumnType("bigint");

                    b.HasKey("PasswordHistoryID")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.HasIndex("UserAccountID");

                    b.ToTable("PasswordHistory", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.UserManagement.PasswordResetAudit", b =>
                {
                    b.Property<long>("PasswordResetAuditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PasswordResetAuditID"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsSuccessfulLoginAfterReset")
                        .HasColumnType("bit");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("UserAccountID")
                        .HasColumnType("bigint");

                    b.HasKey("PasswordResetAuditID");

                    b.HasIndex("UserAccountID", "CreatedDate");

                    b.ToTable("PasswordResetAudits", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.UserManagement.UserAccount", b =>
                {
                    b.Property<long>("UserAccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserAccountID"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUserPartialDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserAccountID")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.HasAlternateKey("UserID");

                    b.ToTable("UserAccount", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.UserManagement.UserLogInfo", b =>
                {
                    b.Property<long>("UserLogInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserLogInfoID"));

                    b.Property<bool>("ActivateNewUser")
                        .HasColumnType("bit");

                    b.Property<string>("ConfirmationToken")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPasswordRecoveryTokenUsed")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastLoginDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LockoutEndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("PasswordrecoveryToken")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTimeOffset?>("RecoveryTokenTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("TokenGenerationTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("UserAccountID")
                        .HasColumnType("bigint");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserLogInfoID");

                    b.HasAlternateKey("UserID");

                    b.HasIndex("UserAccountID")
                        .IsUnique();

                    b.ToTable("UserLogInfo", "CBSAP");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Entity.EntityMatchingConfig", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.Entity.EntityProfile", "EntityProfile")
                        .WithMany("MatchingConfigs")
                        .HasForeignKey("EntityProfileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityProfile");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Invoicing.Account", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.Entity.EntityProfile", "EntityProfile")
                        .WithOne("Account")
                        .HasForeignKey("CbsAp.Domain.Entities.Invoicing.Account", "EntityProfileID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CbsAp.Domain.Entities.TaxCodes.TaxCode", "TaxCode")
                        .WithOne("Account")
                        .HasForeignKey("CbsAp.Domain.Entities.Invoicing.Account", "TaxCodeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EntityProfile");

                    b.Navigation("TaxCode");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Invoicing.InvAllocLine", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.Invoicing.Invoice", "Invoice")
                        .WithMany("InvoiceAllocationLines")
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CbsAp.Domain.Entities.TaxCodes.TaxCode", "TaxCode")
                        .WithMany()
                        .HasForeignKey("TaxCodeID");

                    b.Navigation("Invoice");

                    b.Navigation("TaxCode");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Invoicing.InvAllocLineDimension", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.Invoicing.InvAllocLine", "AllocationLine")
                        .WithMany("Dimensions")
                        .HasForeignKey("InvAllocLineID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AllocationLine");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Invoicing.InvAllocLineFreeField", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.Invoicing.InvAllocLine", "AllocationLine")
                        .WithMany("FreeFields")
                        .HasForeignKey("InvAllocLineID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AllocationLine");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Invoicing.InvRoutingFlow", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.Entity.EntityProfile", "EntityProfile")
                        .WithMany()
                        .HasForeignKey("EntityProfileID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CbsAp.Domain.Entities.Supplier.SupplierInfo", "SupplierInfo")
                        .WithMany()
                        .HasForeignKey("SupplierInfoID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EntityProfile");

                    b.Navigation("SupplierInfo");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Invoicing.InvRoutingFlowLevels", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.Invoicing.InvRoutingFlow", "InvRoutingFlow")
                        .WithMany("Levels")
                        .HasForeignKey("InvRoutingFlowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CbsAp.Domain.Entities.RoleManagement.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvRoutingFlow");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Invoicing.Invoice", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.Entity.EntityProfile", "EntityProfile")
                        .WithMany()
                        .HasForeignKey("EntityProfileID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CbsAp.Domain.Entities.Supplier.SupplierInfo", "SupplierInfo")
                        .WithMany()
                        .HasForeignKey("SupplierInfoID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CbsAp.Domain.Entities.TaxCodes.TaxCode", "TaxCode")
                        .WithMany()
                        .HasForeignKey("TaxCodeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CbsAp.Domain.Entities.Invoicing.FreeFieldSets", "FreeFields", b1 =>
                        {
                            b1.Property<long>("InvoiceID")
                                .HasColumnType("bigint");

                            b1.Property<string>("FreeField1")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("FreeField1");

                            b1.Property<string>("FreeField2")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("FreeField2");

                            b1.Property<string>("FreeField3")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("FreeField3");

                            b1.HasKey("InvoiceID");

                            b1.ToTable("Invoice", "CBSAP");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceID");
                        });

                    b.OwnsOne("CbsAp.Domain.Entities.Invoicing.SpareAmountSets", "SpareAmount", b1 =>
                        {
                            b1.Property<long>("InvoiceID")
                                .HasColumnType("bigint");

                            b1.Property<decimal?>("SpareAmount1")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("SpareAmount1");

                            b1.Property<decimal?>("SpareAmount2")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("SpareAmount2");

                            b1.Property<decimal?>("SpareAmount3")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("SpareAmount3");

                            b1.HasKey("InvoiceID");

                            b1.ToTable("Invoice", "CBSAP");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceID");
                        });

                    b.Navigation("EntityProfile");

                    b.Navigation("FreeFields")
                        .IsRequired();

                    b.Navigation("SpareAmount")
                        .IsRequired();

                    b.Navigation("SupplierInfo");

                    b.Navigation("TaxCode");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Invoicing.InvoiceActivityLog", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.Invoicing.Invoice", "Invoice")
                        .WithMany("InvoiceActivityLog")
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Invoicing.InvoiceAttachnment", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.Invoicing.Invoice", "Invoice")
                        .WithMany("InvoiceAttachnments")
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Invoicing.InvoiceComment", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.Invoicing.Invoice", "Invoice")
                        .WithMany("InvoiceComments")
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PO.PurchaseOrder", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.Entity.EntityProfile", "EntityProfile")
                        .WithMany()
                        .HasForeignKey("EntityProfileID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CbsAp.Domain.Entities.Supplier.SupplierInfo", "SupplierInfo")
                        .WithMany()
                        .HasForeignKey("SupplierInfoID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EntityProfile");

                    b.Navigation("SupplierInfo");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PO.PurchaseOrderLine", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.Invoicing.Account", "Account")
                        .WithMany("PurchaseOrderLines")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CbsAp.Domain.Entities.PO.PurchaseOrder", "PurchaseOrder")
                        .WithMany("PurchaseOrderLines")
                        .HasForeignKey("PurchaseOrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CbsAp.Domain.Entities.TaxCodes.TaxCode", "TaxCode")
                        .WithMany("PurchaseOrderLines")
                        .HasForeignKey("TaxCodeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("TaxCode");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PO.PurchaseOrderMatchTracking", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.Invoicing.InvAllocLine", "InvAllocLine")
                        .WithMany("PurchaseOrderMatchTrackings")
                        .HasForeignKey("InvAllocLineID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CbsAp.Domain.Entities.Invoicing.Invoice", "Invoice")
                        .WithMany("PurchaseOrderMatchTrackings")
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CbsAp.Domain.Entities.PO.PurchaseOrder", "PurchaseOrder")
                        .WithMany("PurchaseOrderMatchTrackings")
                        .HasForeignKey("PurchaseOrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CbsAp.Domain.Entities.PO.PurchaseOrderLine", "PurchaseOrderLine")
                        .WithMany("PurchaseOrderMatchTrackings")
                        .HasForeignKey("PurchaseOrderLineID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InvAllocLine");

                    b.Navigation("Invoice");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("PurchaseOrderLine");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.ControlElement", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.PermissionManagement.Operation", "Operation")
                        .WithOne("ControlElement")
                        .HasForeignKey("CbsAp.Domain.Entities.PermissionManagement.ControlElement", "OperationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.Menu", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.PermissionManagement.Operation", "Operation")
                        .WithMany("Menus")
                        .HasForeignKey("OperationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.MenuItem", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.PermissionManagement.Menu", "Menu")
                        .WithMany("MenuItems")
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.PermissionGroup", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.PermissionManagement.Operation", "Operations")
                        .WithMany("PermissionGroups")
                        .HasForeignKey("OperationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CbsAp.Domain.Entities.PermissionManagement.Permission", "Permission")
                        .WithMany("PermissionGroups")
                        .HasForeignKey("PermissionID");

                    b.Navigation("Operations");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.RolePermissionGroup", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.PermissionManagement.PermissionGroup", null)
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionGroupID");

                    b.HasOne("CbsAp.Domain.Entities.PermissionManagement.Permission", "Permission")
                        .WithMany("RolePermissionGroups")
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CbsAp.Domain.Entities.RoleManagement.Role", "Role")
                        .WithMany("RolePermissionGroups")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.RoleManagement.Role", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.RoleManagement.Role", "RelatedRoleManager1")
                        .WithMany()
                        .HasForeignKey("RoleManager1");

                    b.HasOne("CbsAp.Domain.Entities.RoleManagement.Role", "RelatedRoleManager2")
                        .WithMany()
                        .HasForeignKey("RoleManager2");

                    b.Navigation("RelatedRoleManager1");

                    b.Navigation("RelatedRoleManager2");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.RoleManagement.RoleEntity", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.Entity.EntityProfile", "EntityProfile")
                        .WithMany("RoleEntities")
                        .HasForeignKey("EntityProfileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CbsAp.Domain.Entities.RoleManagement.Role", "Role")
                        .WithMany("RoleEntities")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityProfile");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.RoleManagement.RoleReminderNotification", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.RoleManagement.Role", "Role")
                        .WithOne("RoleReminderNotification")
                        .HasForeignKey("CbsAp.Domain.Entities.RoleManagement.RoleReminderNotification", "RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.RoleManagement.UserRole", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.RoleManagement.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CbsAp.Domain.Entities.UserManagement.UserAccount", "UserAccount")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserAccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Supplier.SupplierInfo", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.Invoicing.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CbsAp.Domain.Entities.Entity.EntityProfile", "EntityProfile")
                        .WithMany()
                        .HasForeignKey("EntityProfileID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CbsAp.Domain.Entities.Invoicing.InvRoutingFlow", "InvRoutingFlow")
                        .WithMany()
                        .HasForeignKey("InvRoutingFlowID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CbsAp.Domain.Entities.TaxCodes.TaxCode", "TaxCode")
                        .WithMany()
                        .HasForeignKey("TaxCodeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("EntityProfile");

                    b.Navigation("InvRoutingFlow");

                    b.Navigation("TaxCode");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.TaxCodes.TaxCode", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.Entity.EntityProfile", "EntityProfile")
                        .WithMany()
                        .HasForeignKey("EntityID");

                    b.Navigation("EntityProfile");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.UserManagement.PasswordHistory", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.UserManagement.UserAccount", "UserAccount")
                        .WithMany("PasswordHistories")
                        .HasForeignKey("UserAccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.UserManagement.PasswordResetAudit", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.UserManagement.UserAccount", "UserAccount")
                        .WithMany("PasswordResetAudits")
                        .HasForeignKey("UserAccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.UserManagement.UserLogInfo", b =>
                {
                    b.HasOne("CbsAp.Domain.Entities.UserManagement.UserAccount", "UserAccount")
                        .WithOne("UserLogInfo")
                        .HasForeignKey("CbsAp.Domain.Entities.UserManagement.UserLogInfo", "UserAccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Entity.EntityProfile", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("MatchingConfigs");

                    b.Navigation("RoleEntities");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Invoicing.Account", b =>
                {
                    b.Navigation("PurchaseOrderLines");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Invoicing.InvAllocLine", b =>
                {
                    b.Navigation("Dimensions");

                    b.Navigation("FreeFields");

                    b.Navigation("PurchaseOrderMatchTrackings");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Invoicing.InvRoutingFlow", b =>
                {
                    b.Navigation("Levels");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.Invoicing.Invoice", b =>
                {
                    b.Navigation("InvoiceActivityLog");

                    b.Navigation("InvoiceAllocationLines");

                    b.Navigation("InvoiceAttachnments");

                    b.Navigation("InvoiceComments");

                    b.Navigation("PurchaseOrderMatchTrackings");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PO.PurchaseOrder", b =>
                {
                    b.Navigation("PurchaseOrderLines");

                    b.Navigation("PurchaseOrderMatchTrackings");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PO.PurchaseOrderLine", b =>
                {
                    b.Navigation("PurchaseOrderMatchTrackings");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.Menu", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.Operation", b =>
                {
                    b.Navigation("ControlElement")
                        .IsRequired();

                    b.Navigation("Menus");

                    b.Navigation("PermissionGroups");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.Permission", b =>
                {
                    b.Navigation("PermissionGroups");

                    b.Navigation("RolePermissionGroups");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.PermissionManagement.PermissionGroup", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.RoleManagement.Role", b =>
                {
                    b.Navigation("RoleEntities");

                    b.Navigation("RolePermissionGroups");

                    b.Navigation("RoleReminderNotification")
                        .IsRequired();

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.TaxCodes.TaxCode", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("PurchaseOrderLines");
                });

            modelBuilder.Entity("CbsAp.Domain.Entities.UserManagement.UserAccount", b =>
                {
                    b.Navigation("PasswordHistories");

                    b.Navigation("PasswordResetAudits");

                    b.Navigation("UserLogInfo")
                        .IsRequired();

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
